/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ConexionBD.Conexion;
import DAO.CRUD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author panch
 */
public class RegistroTrabajador extends javax.swing.JFrame implements CRUD {

    Conexion conexion = new Conexion();
    Connection con = conexion.conectar();
    PreparedStatement ps;
    ResultSet rs;
    String modificar;

    public RegistroTrabajador() {
        initComponents();
        limpiar();
        listar();
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PanelPrincipal = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblNombreDistribuidor = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblBuscar = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTrabajador = new javax.swing.JTable();
        lblDireccionDistribuidor = new javax.swing.JLabel();
        txtDireccionTrabajador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTrabajador = new javax.swing.JLabel();
        txtRutTrabajador = new javax.swing.JFormattedTextField();
        txtNombreTrabajador = new javax.swing.JFormattedTextField();
        txtApellidoPTrabajador = new javax.swing.JFormattedTextField();
        txtApellidoMTrabajador = new javax.swing.JFormattedTextField();
        txtCorreoTrabajador = new javax.swing.JTextField();
        txtTelefonoTrabajador = new javax.swing.JFormattedTextField();
        comboTrabajador = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        fechaContratacion = new com.toedter.calendar.JDateChooser();
        Fondo1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAutor = new javax.swing.JMenu();
        RegistrarAutor = new javax.swing.JMenuItem();
        MenuCategoria = new javax.swing.JMenu();
        RegistrarCategoria = new javax.swing.JMenuItem();
        MenuDistribuidor = new javax.swing.JMenu();
        RegistrarDistribuidor = new javax.swing.JMenuItem();
        MenuEditorial = new javax.swing.JMenu();
        RegistrarEditorial = new javax.swing.JMenuItem();
        MenuIdioma = new javax.swing.JMenu();
        RegistrarIdioma = new javax.swing.JMenuItem();
        MenuLibros = new javax.swing.JMenu();
        RegistrarLibros = new javax.swing.JMenuItem();
        MenuMetodosPago = new javax.swing.JMenu();
        RegistrarMetodoPago = new javax.swing.JMenuItem();
        MenuEstados = new javax.swing.JMenu();
        RegistrarEstadoLibro = new javax.swing.JMenuItem();
        MenuTrabajador = new javax.swing.JMenu();
        RegistrarTrabajador = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Registrar Trabajador");
        PanelPrincipal.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 430, 50));

        lblRut.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        lblRut.setForeground(new java.awt.Color(255, 255, 255));
        lblRut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRut.setText("RUT");
        PanelPrincipal.add(lblRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 90, 20));

        lblNombreDistribuidor.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        lblNombreDistribuidor.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreDistribuidor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreDistribuidor.setText("Nombre");
        PanelPrincipal.add(lblNombreDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 110, 20));

        lblTelefono.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefono.setText("Teléfono");
        PanelPrincipal.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 120, 20));
        PanelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 800, 10));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));
        PanelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));
        PanelPrincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));
        PanelPrincipal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 800, 10));

        lblBuscar.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscar.setText("Buscar por");
        PanelPrincipal.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, 20));
        PanelPrincipal.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 120, -1));

        tablaTrabajador = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablaTrabajador.setAutoCreateRowSorter(true);
        tablaTrabajador.setBackground(new java.awt.Color(0, 204, 255));
        tablaTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        tablaTrabajador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tablaTrabajador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaTrabajador.setSelectionBackground(new java.awt.Color(153, 255, 0));
        tablaTrabajador.getTableHeader().setReorderingAllowed(false);
        tablaTrabajador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTrabajadorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaTrabajador);
        tablaTrabajador.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        PanelPrincipal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 630, 150));

        lblDireccionDistribuidor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblDireccionDistribuidor.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionDistribuidor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDireccionDistribuidor.setText("Direccion");
        PanelPrincipal.add(lblDireccionDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 90, -1));
        PanelPrincipal.add(txtDireccionTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 160, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apellido Paterno");
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, 20));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Apellido Materno");
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 100, 20));

        lblCorreo.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCorreo.setText("Correo Electrónico");
        PanelPrincipal.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 110, 20));

        lblTrabajador.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblTrabajador.setForeground(new java.awt.Color(255, 255, 255));
        lblTrabajador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrabajador.setText("Fecha Contratación");
        PanelPrincipal.add(lblTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 110, 20));

        try {
            txtRutTrabajador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRutTrabajador.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        PanelPrincipal.add(txtRutTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, -1));

        try {
            txtNombreTrabajador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("???????????????????????????????")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNombreTrabajador.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        PanelPrincipal.add(txtNombreTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 160, -1));

        try {
            txtApellidoPTrabajador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("????????????????????")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtApellidoPTrabajador.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        PanelPrincipal.add(txtApellidoPTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, -1));

        try {
            txtApellidoMTrabajador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("????????????????????")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtApellidoMTrabajador.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        PanelPrincipal.add(txtApellidoMTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 160, -1));
        PanelPrincipal.add(txtCorreoTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, -1));

        try {
            txtTelefonoTrabajador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefonoTrabajador.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        PanelPrincipal.add(txtTelefonoTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, -1));

        PanelPrincipal.add(comboTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 110, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 100, -1));

        fechaContratacion.setMaxSelectableDate(new java.util.Date(4102459295000L));
        fechaContratacion.setMinSelectableDate(new java.util.Date(-2208971774000L));
        PanelPrincipal.add(fechaContratacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 160, -1));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.jpg"))); // NOI18N
        PanelPrincipal.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        MenuAutor.setText("Autor");

        RegistrarAutor.setText("Registrar");
        RegistrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarAutorActionPerformed(evt);
            }
        });
        MenuAutor.add(RegistrarAutor);

        jMenuBar1.add(MenuAutor);

        MenuCategoria.setText("Categoría");

        RegistrarCategoria.setText("Registrar");
        RegistrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarCategoriaActionPerformed(evt);
            }
        });
        MenuCategoria.add(RegistrarCategoria);

        jMenuBar1.add(MenuCategoria);

        MenuDistribuidor.setText("Distribuidor");

        RegistrarDistribuidor.setText("Registrar");
        RegistrarDistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarDistribuidorActionPerformed(evt);
            }
        });
        MenuDistribuidor.add(RegistrarDistribuidor);

        jMenuBar1.add(MenuDistribuidor);

        MenuEditorial.setText("Editorial");

        RegistrarEditorial.setText("Registrar");
        RegistrarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEditorialActionPerformed(evt);
            }
        });
        MenuEditorial.add(RegistrarEditorial);

        jMenuBar1.add(MenuEditorial);

        MenuIdioma.setText("Idioma");

        RegistrarIdioma.setText("Registrar");
        RegistrarIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarIdiomaActionPerformed(evt);
            }
        });
        MenuIdioma.add(RegistrarIdioma);

        jMenuBar1.add(MenuIdioma);

        MenuLibros.setText("Libros");

        RegistrarLibros.setText("Registrar");
        RegistrarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarLibrosActionPerformed(evt);
            }
        });
        MenuLibros.add(RegistrarLibros);

        jMenuBar1.add(MenuLibros);

        MenuMetodosPago.setText("Metodos de Pago");

        RegistrarMetodoPago.setText("Registrar");
        RegistrarMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarMetodoPagoActionPerformed(evt);
            }
        });
        MenuMetodosPago.add(RegistrarMetodoPago);

        jMenuBar1.add(MenuMetodosPago);

        MenuEstados.setText("Estado Libros");

        RegistrarEstadoLibro.setText("Registrar");
        RegistrarEstadoLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarEstadoLibroActionPerformed(evt);
            }
        });
        MenuEstados.add(RegistrarEstadoLibro);

        jMenuBar1.add(MenuEstados);

        MenuTrabajador.setText("Trabajador");

        RegistrarTrabajador.setText("Registrar");
        RegistrarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarTrabajadorActionPerformed(evt);
            }
        });
        MenuTrabajador.add(RegistrarTrabajador);

        jMenuBar1.add(MenuTrabajador);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        insertar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarPor();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaTrabajadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTrabajadorMouseClicked
        if (evt.getClickCount() == 2) {
            int filaSeleccionada = tablaTrabajador.getSelectedRow();
            modificar = tablaTrabajador.getValueAt(filaSeleccionada, 0).toString().trim();

            String RUT = tablaTrabajador.getValueAt(filaSeleccionada, 0).toString().trim();
            String Nombre = tablaTrabajador.getValueAt(filaSeleccionada, 1).toString().trim();
            String ApellidoP = tablaTrabajador.getValueAt(filaSeleccionada, 2).toString().trim();
            String ApellidoM = tablaTrabajador.getValueAt(filaSeleccionada, 3).toString().trim();
            String correo = tablaTrabajador.getValueAt(filaSeleccionada, 4).toString().trim();
            Date fecha = (Date) tablaTrabajador.getValueAt(filaSeleccionada, 5);
            String telefono = tablaTrabajador.getValueAt(filaSeleccionada, 6).toString().trim();
            String calle = tablaTrabajador.getValueAt(filaSeleccionada, 7).toString().trim();

            txtRutTrabajador.setText(RUT);
            txtNombreTrabajador.setText(Nombre);
            txtApellidoPTrabajador.setText(ApellidoP);
            txtApellidoMTrabajador.setText(ApellidoM);
            txtCorreoTrabajador.setText(correo);
            fechaContratacion.setDate(fecha);
            txtTelefonoTrabajador.setText(telefono);
            txtDireccionTrabajador.setText(calle);
        }
    }//GEN-LAST:event_tablaTrabajadorMouseClicked

    private void RegistrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarAutorActionPerformed
        RegistroAutor registroAutor = new RegistroAutor();
        registroAutor.setVisible(true);
        registroAutor.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_RegistrarAutorActionPerformed

    private void RegistrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarCategoriaActionPerformed
        RegistroCategoria registroCategoria = new RegistroCategoria();
        registroCategoria.setVisible(true);
        registroCategoria.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_RegistrarCategoriaActionPerformed

    private void RegistrarDistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarDistribuidorActionPerformed
        RegistroDistribuidor registroDistribuidor = new RegistroDistribuidor();
        registroDistribuidor.setVisible(true);
        registroDistribuidor.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_RegistrarDistribuidorActionPerformed

    private void RegistrarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEditorialActionPerformed
        RegistroEditorial registroEditorial = new RegistroEditorial();
        registroEditorial.setVisible(true);
        registroEditorial.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_RegistrarEditorialActionPerformed

    private void RegistrarIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarIdiomaActionPerformed
        RegistroIdioma registroIdioma = new RegistroIdioma();
        registroIdioma.setVisible(true);
        registroIdioma.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_RegistrarIdiomaActionPerformed

    private void RegistrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarLibrosActionPerformed
        RegistroLibro registroLibro = new RegistroLibro();
        registroLibro.setVisible(true);
        registroLibro.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_RegistrarLibrosActionPerformed

    private void RegistrarMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarMetodoPagoActionPerformed
        RegistroMetodoPago metodoPago = new RegistroMetodoPago();
        metodoPago.setVisible(true);
        metodoPago.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_RegistrarMetodoPagoActionPerformed

    private void RegistrarEstadoLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarEstadoLibroActionPerformed
        RegistroEstadoLibro registroEstadoLibro = new RegistroEstadoLibro();
        registroEstadoLibro.setVisible(true);
        registroEstadoLibro.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_RegistrarEstadoLibroActionPerformed

    private void RegistrarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarTrabajadorActionPerformed
        RegistroTrabajador registroTrabajador = new RegistroTrabajador();
        registroTrabajador.setVisible(true);
        registroTrabajador.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_RegistrarTrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo1;
    private javax.swing.JMenu MenuAutor;
    private javax.swing.JMenu MenuCategoria;
    private javax.swing.JMenu MenuDistribuidor;
    private javax.swing.JMenu MenuEditorial;
    private javax.swing.JMenu MenuEstados;
    private javax.swing.JMenu MenuIdioma;
    private javax.swing.JMenu MenuLibros;
    private javax.swing.JMenu MenuMetodosPago;
    private javax.swing.JMenu MenuTrabajador;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JMenuItem RegistrarAutor;
    private javax.swing.JMenuItem RegistrarCategoria;
    private javax.swing.JMenuItem RegistrarDistribuidor;
    private javax.swing.JMenuItem RegistrarEditorial;
    private javax.swing.JMenuItem RegistrarEstadoLibro;
    private javax.swing.JMenuItem RegistrarIdioma;
    private javax.swing.JMenuItem RegistrarLibros;
    private javax.swing.JMenuItem RegistrarMetodoPago;
    private javax.swing.JMenuItem RegistrarTrabajador;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboTrabajador;
    private com.toedter.calendar.JDateChooser fechaContratacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDireccionDistribuidor;
    private javax.swing.JLabel lblNombreDistribuidor;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTrabajador;
    private javax.swing.JTable tablaTrabajador;
    private javax.swing.JFormattedTextField txtApellidoMTrabajador;
    private javax.swing.JFormattedTextField txtApellidoPTrabajador;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCorreoTrabajador;
    private javax.swing.JTextField txtDireccionTrabajador;
    private javax.swing.JFormattedTextField txtNombreTrabajador;
    private javax.swing.JFormattedTextField txtRutTrabajador;
    private javax.swing.JFormattedTextField txtTelefonoTrabajador;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiar() {
        txtRutTrabajador.setText("");
        txtNombreTrabajador.setText("");
        txtApellidoPTrabajador.setText("");
        txtApellidoMTrabajador.setText("");
        txtCorreoTrabajador.setText("");
        String fecha = "01-01-0001";
        Date fechasql = devolverFecha(fecha);
        fechaContratacion.setDate(fechasql);
        txtTelefonoTrabajador.setText("");
        txtDireccionTrabajador.setText("");
        txtBusqueda.setText("");
    }

    public Date devolverFecha(String fecha) {
        Date fechasql = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-DD");
            fechasql = sdf.parse(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(RegistroTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
        return fechasql;
    }

    @Override
    public void modificar() {
        try {
            String rut = txtRutTrabajador.getText().trim();
            String nombre = txtNombreTrabajador.getText().trim();
            String ApellidoP = txtApellidoPTrabajador.getText().trim();
            String ApellidoM = txtApellidoMTrabajador.getText().trim();
            String correo = txtCorreoTrabajador.getText().trim();
            Date fechacon = fechaContratacion.getDate();
            java.sql.Date fechaentra = new java.sql.Date(fechacon.getTime());
            String telefono = txtTelefonoTrabajador.getText().trim();
            String calle = txtDireccionTrabajador.getText().trim();
            String sql = "UPDATE Trabajador SET RUT='" + rut + "', NOMBRE='" + nombre + "', APELLIDO_PATERNO='" + ApellidoP + "', APELLIDO_MATERNO='" + ApellidoM + "'"
                    + ",CORREO_ELECTRÓNICO ='" + correo + "',FECHA_CONTRATACIÓN = TO_DATE('" + fechaentra + "','YYYY-MM-DD')"
                    + ", TELEFONO='" + telefono + "' , CALLE='" + calle + "' WHERE RUT ='" + modificar + "'";
            ps = con.prepareStatement(sql);
            int res = ps.executeUpdate();
            if (res > 0) {
                limpiar();
                listar();
                JOptionPane.showMessageDialog(null, "Se ha modificar satisfactoriamente su registro", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            //JOptionPane.showMessageDialog(null, "Ya existe el RUT en nuestra Base de datos", "Confirmación", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void llenarCombo() {
        try {
            String sql = "SELECT * FROM Trabajador";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int cantColumnas = rsmd.getColumnCount();
            for (int i = 1; i <= cantColumnas; i++) {
                comboTrabajador.addItem(rsmd.getColumnName(i));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistroAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void insertar() {
        try {
            String sql = "INSERT INTO Trabajador VALUES(?,?,?,?,?,TO_DATE(?,'YYYY-MM-DD'),?,?)";
            ps = con.prepareStatement(sql);
            ps.setString(1, txtRutTrabajador.getText().trim());
            ps.setString(2, txtNombreTrabajador.getText().trim());
            ps.setString(3, txtApellidoPTrabajador.getText().trim());
            ps.setString(4, txtApellidoMTrabajador.getText().trim());
            ps.setString(5, txtCorreoTrabajador.getText().trim());
            Date fecha = fechaContratacion.getDate();
            ps.setDate(6, new java.sql.Date(fecha.getTime()));

            ps.setString(7, txtTelefonoTrabajador.getText().trim());
            ps.setString(8, txtDireccionTrabajador.getText().trim());

            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Se ha ingresado correctamente el valor a la BD", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                listar();
            }

        } catch (SQLException ex) {

            if (txtRutTrabajador.getText().trim().equals(".   .   -")) {
                JOptionPane.showMessageDialog(null, "No se ingresó RUT", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtRutTrabajador.getText().trim().length() < 11) {
                JOptionPane.showMessageDialog(null, "Su Rut está mal formado", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtNombreTrabajador.getText().trim().length() == 0 || txtNombreTrabajador.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "No se ingresó Nombre", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtApellidoPTrabajador.getText().trim().length() == 0 || txtApellidoPTrabajador.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "No se ingresó el Apellido Paterno", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            } else if (txtCorreoTrabajador.getText().trim().length() == 0 || txtCorreoTrabajador.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "No se ingresó el Apellido Materno", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }
            else if (txtTelefonoTrabajador.getText().trim().length() == 1 || txtCorreoTrabajador.getText().trim().equals("-")) {
                JOptionPane.showMessageDialog(null, "No se ingresó el Telefono", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }else {
                JOptionPane.showMessageDialog(null, "No se ha ingresado correctamente a la BD, ya está ese nombre en uso", "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }

    @Override
    public void eliminar() {

        int filaseleccionada;
        filaseleccionada = tablaTrabajador.getSelectedRow();
        if (filaseleccionada >= 0) {
            try {
                int seleccionar = JOptionPane.showConfirmDialog(null, "¿Desea Eliminar este Registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
                if (seleccionar == 0) {
                    String sql = "DELETE FROM Trabajador WHERE RUT = ?";
                    String valor = tablaTrabajador.getValueAt(filaseleccionada, 0).toString();
                    ps = con.prepareStatement(sql);
                    ps.setString(1, valor);
                    int res = ps.executeUpdate();
                    if (res > 0) {
                        JOptionPane.showMessageDialog(null, "Se ha Eliminado Correctamente el registro", "Mensaje de Eliminación", JOptionPane.INFORMATION_MESSAGE);
                        listar();
                    }
                }
            } catch (SQLException ex) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila para eliminar", "Ventana", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void listar() {
        DefaultTableModel modelo = new DefaultTableModel();
        try {
            String sql = "SELECT * FROM Trabajador";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int cantColumnas = rsmd.getColumnCount();
            modelo.addColumn("RUT");
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido Paterno");
            modelo.addColumn("Apellido Materno");
            modelo.addColumn("Correo Electrónico");
            modelo.addColumn("Fecha de Contratación");
            modelo.addColumn("Número Telefónico");
            modelo.addColumn("Calle");

            while (rs.next()) {
                Object[] filas = new Object[cantColumnas];
                for (int i = 0; i < cantColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }
            tablaTrabajador.setModel(modelo);
        } catch (SQLException ex) {

        }
    }

    @Override
    public void buscarPor() {
        DefaultTableModel modelo = new DefaultTableModel();
        try {
            String datoCombo = (String) comboTrabajador.getSelectedItem();
            String buscar = txtBusqueda.getText().trim();
            if (buscar.equals("")) {
                listar();
            } else {
                String sql = "SELECT * FROM Trabajador WHERE UPPER(" + datoCombo + ")  like UPPER('%" + buscar + "%') ";
                ps = con.prepareStatement(sql);
                rs = ps.executeQuery();
                ResultSetMetaData rsmd = rs.getMetaData();
                int cantColumnas = rsmd.getColumnCount();
                modelo.addColumn("RUT");
                modelo.addColumn("Nombre");
                modelo.addColumn("Apellido Paterno");
                modelo.addColumn("Apellido Materno");
                modelo.addColumn("Correo Electrónico");
                modelo.addColumn("Fecha de Contratación");
                modelo.addColumn("Número Telefónico");
                modelo.addColumn("Calle");
                while (rs.next()) {
                    Object[] filas = new Object[cantColumnas];
                    for (int i = 0; i < cantColumnas; i++) {
                        filas[i] = rs.getObject(i + 1);
                    }
                    modelo.addRow(filas);
                }
                tablaTrabajador.setModel(modelo);
            }

        } catch (SQLException ex) {
            Logger.getLogger(RegistroAutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
